services:
  - type: web
    name: prime-shop-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/primeshop-0.0.1-SNAPSHOT.jar
    # envVars:
    #   - key: JAVA_HOME
    #     value: /usr/lib/jvm/java-17-openjdk-amd64
